spring:
  security:
    oauth2:
      client:
        registration:
          uaa:
            client-id: your-client-id
            client-secret: your-client-secret
            scope: openid,profile,email
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          uaa:
            issuer-uri: https://your-auth-server.com/oauth2/default
  cloud:
    gateway:
      routes:
        - id: protected_resource_route
          uri: http://localhost:8084 # Servizio protetto
          predicates:
            - Path=/api/protected/**
          filters:
            - TokenRelay # Inoltra il token OAuth2 al servizio backend