spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
           routes:
             - id: authentication_service
               uri: lb://AUTHENTICATION-SERVICE
               predicates:
                 - Path=/auth/**
               filters:
                 - name: RequestRateLimiter
                   args:
                     key-resolver: '#{@ipKeyResolver}' 
                     redis-rate-limiter.replenishRate: 5 
                     redis-rate-limiter.burstCapacity: 10 
                     redis-rate-limiter.requestedTokens: 1 