spring:
  cloud:
    gateway:
      routes:
        - id: book-service-route
          uri: lb://BOOK-SERVICE # Nome del servizio utilizzando Eureka
          predicates:
            - Path=/api/books/** # Predicato di percorso
          filters:
            - StripPrefix=2 # Rimuove /api/books dal percorso prima di inoltrare